// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4rhSuvn2vuO5hZYcnqWlmnAmQr3umRZc',
    appId: '1:871978926212:web:bba370cf9e36e3314102d1',
    messagingSenderId: '871978926212',
    projectId: 'shopzone-59ce9',
    authDomain: 'shopzone-59ce9.firebaseapp.com',
    storageBucket: 'shopzone-59ce9.appspot.com',
    measurementId: 'G-F75Z0GTDNP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsm3SEyq5l6jOmwEyZey1JWy1xK9inYls',
    appId: '1:871978926212:android:ff6fcfd8d80979994102d1',
    messagingSenderId: '871978926212',
    projectId: 'shopzone-59ce9',
    storageBucket: 'shopzone-59ce9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAH6uV9CgRz-V8r2RPMIKKPiokFHpNHhs',
    appId: '1:871978926212:ios:a463e9efbdf77faa4102d1',
    messagingSenderId: '871978926212',
    projectId: 'shopzone-59ce9',
    storageBucket: 'shopzone-59ce9.appspot.com',
    iosClientId: '871978926212-m8fiboa0ubmuq3ga0n1i4u7tb98v6p0f.apps.googleusercontent.com',
    iosBundleId: 'com.example.shopzonee',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAH6uV9CgRz-V8r2RPMIKKPiokFHpNHhs',
    appId: '1:871978926212:ios:a463e9efbdf77faa4102d1',
    messagingSenderId: '871978926212',
    projectId: 'shopzone-59ce9',
    storageBucket: 'shopzone-59ce9.appspot.com',
    iosClientId: '871978926212-m8fiboa0ubmuq3ga0n1i4u7tb98v6p0f.apps.googleusercontent.com',
    iosBundleId: 'com.example.shopzonee',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB4rhSuvn2vuO5hZYcnqWlmnAmQr3umRZc',
    appId: '1:871978926212:web:03fede8002df2da84102d1',
    messagingSenderId: '871978926212',
    projectId: 'shopzone-59ce9',
    authDomain: 'shopzone-59ce9.firebaseapp.com',
    storageBucket: 'shopzone-59ce9.appspot.com',
    measurementId: 'G-W7J3Y50SLM',
  );

}